#!/usr/bin/env python3
"""Regenerate / verify scripts/dsh-gate0/known-event-types.txt against the
pinned DSH source `KNOWN_SESSION_EVENT_TYPES` Set literal.

Round9 P2: the previous regeneration hint was a non-runnable `node -e` snippet
with an ellipsis. Round10 P2: `--write` must preserve the pinned SHA (read from
DSH_ROOT's git HEAD, never hand-typed) and the ignorable-semantics block, and
the script must run on Python 3.9 (macOS system Python) — hence
`from __future__ import annotations`.

Usage:
  DSH_ROOT=/path/to/deepseek-harness python3 gen-known-event-types.py          # verify
  DSH_ROOT=/path/to/deepseek-harness python3 gen-known-event-types.py --write   # regenerate
  python3 gen-known-event-types.py --src /abs/path/known-event-types.ts         # explicit src (verify only)
"""
from __future__ import annotations

import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TXT = os.path.join(HERE, "known-event-types.txt")
DEFAULT_SRC = "packages/core/session/src/known-event-types.ts"
# match single-quoted event names inside the Set literal
EVENT_RE = re.compile(r"'([A-Za-z][A-Za-z0-9_./-]*)'")

SEMANTICS = """#
# Semantics (per source comment + SessionEvent.ignorable in core/session/src/types.ts):
#   Membership ONLY means "this build recognizes the name + schema".
#   It is NOT "safe to ignore". A reader may skip an event ONLY when the
#   envelope carries ignorable:true; absence means REQUIRED and an
#   unrecognized/unimplemented required event MUST refuse reconstruction.
#"""

USAGE_LINES = """# Regenerate / verify this snapshot with the executable script:
#   DSH_ROOT=/path/to/deepseek-harness python3 scripts/dsh-gate0/gen-known-event-types.py           # verify (exits non-zero on drift)
#   DSH_ROOT=/path/to/deepseek-harness python3 scripts/dsh-gate0/gen-known-event-types.py --write  # regenerate
"""


def resolve_src(arg_src):
    if arg_src:
        return arg_src, None
    root = os.environ.get("DSH_ROOT")
    if not root:
        sys.exit("error: set DSH_ROOT or pass --src <known-event-types.ts>")
    return os.path.join(root, DEFAULT_SRC), root


def git_head_sha(root):
    """Exact pinned SHA from the DSH checkout itself (round10 P2: never hand-typed)."""
    try:
        out = subprocess.run(
            ["git", "-C", root, "rev-parse", "HEAD"],
            capture_output=True, text=True, check=True,
        )
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        sys.exit(f"error: could not read git HEAD SHA from DSH_ROOT={root}: {e}")


def extract_types(src_path):
    text = open(src_path, encoding="utf-8").read()
    # isolate the KNOWN_SESSION_EVENT_TYPES Set block
    m = re.search(r"KNOWN_SESSION_EVENT_TYPES[^=]*=\s*new Set\(\[(.*?)\]\)", text, re.S)
    if not m:
        sys.exit(f"error: could not find KNOWN_SESSION_EVENT_TYPES Set in {src_path}")
    return EVENT_RE.findall(m.group(1))


def committed_types():
    out = []
    for line in open(TXT, encoding="utf-8"):
        s = line.strip()
        if s and not s.startswith("#"):
            out.append(s)
    return out


def build_header(sha, count):
    lines = [
        "# DSH `KNOWN_SESSION_EVENT_TYPES` — pinned frozen inventory",
        "#",
        f"# Source of truth: deepseek-harness@{sha}",
        f"#   {DEFAULT_SRC}",
        "# Generated by scripts/dsh-gate0/gen-known-event-types.py --write",
    ]
    lines.extend(USAGE_LINES.rstrip("\n").split("\n"))
    lines.append(SEMANTICS.rstrip("\n"))
    lines.append("#")
    lines.append(f"# Count: {count}")
    return "\n".join(lines) + "\n"


def main():
    args = sys.argv[1:]
    do_write = "--write" in args
    src = None
    for i, a in enumerate(args):
        if a == "--src" and i + 1 < len(args):
            src = args[i + 1]
    src_path, root = resolve_src(src)
    types = extract_types(src_path)
    if len(types) != len(set(types)):
        sys.exit(f"error: source Set has duplicates: {len(types)} entries, {len(set(types))} unique")
    if do_write:
        if root is None:
            sys.exit("error: --write requires DSH_ROOT (to stamp the git HEAD SHA); --src alone is verify-only")
        sha = git_head_sha(root)
        with open(TXT, "w", encoding="utf-8") as f:
            f.write(build_header(sha, len(types)))
            f.write("\n".join(types) + "\n")
        print(f"wrote {len(types)} types (pinned {sha[:12]}) to {TXT}")
        return 0
    committed = committed_types()
    src_set, com_set = set(types), set(committed)
    if src_set == com_set:
        print(f"OK: source==artifact, {len(types)} types (sorted-equal)")
        return 0
    print(f"DRIFT: source={len(src_set)} artifact={len(com_set)}")
    print("  missing from artifact:", sorted(src_set - com_set))
    print("  extra in artifact:", sorted(com_set - src_set))
    return 1


if __name__ == "__main__":
    sys.exit(main())
