#!/usr/bin/env python3
"""Regenerate / verify scripts/dsh-gate0/known-event-types.txt against the
pinned DSH source `KNOWN_SESSION_EVENT_TYPES` Set literal.

Round9 P2: the previous regeneration hint was a non-runnable `node -e` snippet
with an ellipsis. This script is the real, executable contract — it parses the
Set literal directly and either rewrites the .txt (--write) or compares against
the committed file (default, exits non-zero on drift).

Usage:
  DSH_ROOT=/path/to/deepseek-harness python3 gen-known-event-types.py          # verify
  DSH_ROOT=/path/to/deepseek-harness python3 gen-known-event-types.py --write   # regenerate
  python3 gen-known-event-types.py --src /abs/path/known-event-types.ts         # explicit src
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TXT = os.path.join(HERE, "known-event-types.txt")
DEFAULT_SRC = "packages/core/session/src/known-event-types.ts"
# match single-quoted event names inside the Set literal
EVENT_RE = re.compile(r"'([A-Za-z][A-Za-z0-9_./-]*)'")


def resolve_src(arg_src: str | None) -> str:
    if arg_src:
        return arg_src
    root = os.environ.get("DSH_ROOT")
    if not root:
        sys.exit("error: set DSH_ROOT or pass --src <known-event-types.ts>")
    return os.path.join(root, DEFAULT_SRC)


def extract_types(src_path: str) -> list[str]:
    text = open(src_path, encoding="utf-8").read()
    # isolate the KNOWN_SESSION_EVENT_TYPES Set block
    m = re.search(r"KNOWN_SESSION_EVENT_TYPES[^=]*=\s*new Set\(\[(.*?)\]\)", text, re.S)
    if not m:
        sys.exit(f"error: could not find KNOWN_SESSION_EVENT_TYPES Set in {src_path}")
    return EVENT_RE.findall(m.group(1))


def committed_types() -> list[str]:
    out = []
    for line in open(TXT, encoding="utf-8"):
        s = line.strip()
        if s and not s.startswith("#"):
            out.append(s)
    return out


def main() -> int:
    args = sys.argv[1:]
    do_write = "--write" in args
    src = None
    for i, a in enumerate(args):
        if a == "--src" and i + 1 < len(args):
            src = args[i + 1]
    types = extract_types(resolve_src(src))
    if len(types) != len(set(types)):
        sys.exit(f"error: source Set has duplicates: {len(types)} entries, {len(set(types))} unique")
    if do_write:
        header = (
            "# DSH `KNOWN_SESSION_EVENT_TYPES` — pinned frozen inventory\n"
            f"# Source of truth: deepseek-harness (run with DSH_ROOT to regenerate)\n"
            f"#   {DEFAULT_SRC}\n"
            f"# Generated by scripts/dsh-gate0/gen-known-event-types.py --write\n"
            f"# Count: {len(types)}\n"
        )
        open(TXT, "w", encoding="utf-8").write(header + "\n".join(types) + "\n")
        print(f"wrote {len(types)} types to {TXT}")
        return 0
    committed = committed_types()
    src_set, com_set = set(types), set(committed)
    if src_set == com_set:
        print(f"OK: source==artifact, {len(types)} types (sorted-equal)")
        return 0
    print(f"DRIFT: source={len(src_set)} artifact={len(com_set)}")
    print("  missing from artifact:", sorted(src_set - com_set))
    print("  extra in artifact:", sorted(com_set - src_set))
    return 1


if __name__ == "__main__":
    sys.exit(main())
