#!/usr/bin/env python3
"""Regenerate / verify scripts/dsh-gate0/known-event-types.txt against the
pinned DSH source `KNOWN_SESSION_EVENT_TYPES` Set literal.

Round9 P2: the previous regeneration hint was a non-runnable `node -e` snippet.
Round10 P2: `--write` must preserve the pinned SHA and ignorable-semantics block,
and run on Python 3.9 (macOS system Python) — hence `from __future__ import annotations`.
Round11 P2: `--write` reads the exact committed blob via `git show HEAD:<path>`
(never the working tree), so a dirty checkout cannot be stamped as clean HEAD;
`verify` also compares the artifact's stamped SHA against DSH ROOT's current HEAD
and reports provenance drift even when the event set is unchanged.

Usage:
  DSH_ROOT=/path/to/deepseek-harness python3 gen-known-event-types.py          # verify (set + provenance)
  DSH_ROOT=/path/to/deepseek-harness python3 gen-known-event-types.py --write  # regenerate from HEAD blob
  python3 gen-known-event-types.py --src /abs/path/known-event-types.ts        # raw-file verify (no SHA check)
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
TXT = os.path.join(HERE, "known-event-types.txt")
DEFAULT_SRC = "packages/core/session/src/known-event-types.ts"
# match single-quoted event names inside the Set literal
EVENT_RE = re.compile(r"'([A-Za-z][A-Za-z0-9_./-]*)'")
# artifact header stamp: "deepseek-harness@<sha>"
SHA_RE = re.compile(r"deepseek-harness@([0-9a-f]{7,40})")

SEMANTICS = """#
# Semantics (per source comment + SessionEvent.ignorable in core/session/src/types.ts):
#   Membership ONLY means "this build recognizes the name + schema".
#   It is NOT "safe to ignore". A reader may skip an event ONLY when the
#   envelope carries ignorable:true; absence means REQUIRED and an
#   unrecognized/unimplemented required event MUST refuse reconstruction.
#"""

USAGE_LINES = """# Regenerate / verify this snapshot with the executable script:
#   DSH_ROOT=/path/to/deepseek-harness python3 scripts/dsh-gate0/gen-known-event-types.py           # verify (set + provenance drift)
#   DSH_ROOT=/path/to/deepseek-harness python3 scripts/dsh-gate0/gen-known-event-types.py --write  # regenerate from HEAD blob
#"""


def git(root, *args):
    try:
        out = subprocess.run(
            ["git", "-C", root, *args],
            capture_output=True, text=True, check=True,
        )
        return out.stdout
    except subprocess.CalledProcessError as e:
        sys.exit(f"error: git {' '.join(args)} failed in {root}: {e.stderr.strip()}")


def repo_root(root):
    toplevel = git(root, "rev-parse", "--show-toplevel").strip()
    if os.path.realpath(root) != os.path.realpath(toplevel):
        sys.exit(f"error: DSH_ROOT={root} is not the git repo root ({toplevel}); point DSH_ROOT at the checkout root")
    return toplevel


def head_blob(root):
    """Exact committed blob (round11 P2): content and SHA always come from the same HEAD."""
    sha = git(root, "rev-parse", "HEAD").strip()
    blob = git(root, "show", f"HEAD:{DEFAULT_SRC}")
    return sha, blob


def extract_types(text, label):
    m = re.search(r"KNOWN_SESSION_EVENT_TYPES[^=]*=\s*new Set\(\[(.*?)\]\)", text, re.S)
    if not m:
        sys.exit(f"error: could not find KNOWN_SESSION_EVENT_TYPES Set in {label}")
    return EVENT_RE.findall(m.group(1))


def artifact_state():
    if not os.path.exists(TXT):
        sys.exit(f"error: artifact not found: {TXT} — run with --write to generate it")
    lines = open(TXT, encoding="utf-8").read()
    types = [s.strip() for s in lines.splitlines() if s.strip() and not s.startswith("#")]
    m = SHA_RE.search(lines)
    return types, (m.group(1) if m else None)


def build_header(sha, count):
    lines = [
        "# DSH `KNOWN_SESSION_EVENT_TYPES` — pinned frozen inventory",
        "#",
        f"# Source of truth: deepseek-harness@{sha}",
        f"#   {DEFAULT_SRC}",
        "# Generated by scripts/dsh-gate0/gen-known-event-types.py --write (from the HEAD blob)",
    ]
    lines.extend(USAGE_LINES.rstrip("\n").split("\n"))
    lines.append(SEMANTICS.rstrip("\n"))
    lines.append("#")
    lines.append(f"# Count: {count}")
    return "\n".join(lines) + "\n"


def main():
    args = sys.argv[1:]
    do_write = "--write" in args
    src = None
    for i, a in enumerate(args):
        if a == "--src" and i + 1 < len(args):
            src = args[i + 1]

    if src:
        if do_write:
            sys.exit("error: --write requires DSH_ROOT (HEAD blob + SHA stamp); --src is verify-only")
        types = extract_types(open(src, encoding="utf-8").read(), src)
        committed, _ = artifact_state()
        src_set, com_set = set(types), set(committed)
        if src_set == com_set:
            print(f"OK (raw-file mode): source==artifact, {len(types)} types (no provenance check)")
            return 0
        print(f"DRIFT (raw-file mode): source={len(src_set)} artifact={len(com_set)}")
        print("  missing from artifact:", sorted(src_set - com_set))
        print("  extra in artifact:", sorted(com_set - src_set))
        return 1

    root = os.environ.get("DSH_ROOT")
    if not root:
        sys.exit("error: set DSH_ROOT or pass --src <known-event-types.ts>")
    repo_root(root)
    sha, blob = head_blob(root)
    types = extract_types(blob, f"HEAD:{DEFAULT_SRC}")
    if len(types) != len(set(types)):
        sys.exit(f"error: source Set has duplicates: {len(types)} entries, {len(set(types))} unique")

    if do_write:
        with open(TXT, "w", encoding="utf-8") as f:
            f.write(build_header(sha, len(types)))
            f.write("\n".join(types) + "\n")
        print(f"wrote {len(types)} types (pinned {sha[:12]}, from HEAD blob) to {TXT}")
        return 0

    committed, art_sha = artifact_state()
    failures = []
    src_set, com_set = set(types), set(committed)
    if src_set != com_set:
        failures.append(f"set drift: source={len(src_set)} artifact={len(com_set)}")
        failures.append("  missing from artifact: " + str(sorted(src_set - com_set)))
        failures.append("  extra in artifact: " + str(sorted(com_set - src_set)))
    if art_sha != sha:
        failures.append(f"provenance drift: artifact stamped {art_sha} but DSH HEAD is {sha} — re-run --write after re-pin")
    if failures:
        print("DRIFT:")
        for f in failures:
            print(" ", f)
        return 1
    print(f"OK: source==artifact, {len(types)} types; artifact SHA == DSH HEAD ({sha[:12]})")
    return 0



# ── package-source mode (owner directive v2 §4): freeze the KNOWN list of an
# INSTALLED dsh-session package (compiled lib/index.js) as a second artifact,
# independent of the pinned source checkout. Usage:
#   python3 gen-known-event-types.py --package-source <path/to/dsh-session/lib/index.js> --write-artifact scripts/dsh-gate0/known-event-types-rc6.txt
#   python3 gen-known-event-types.py --package-source <...>   # verify existing artifact
def extract_package_known_types(js_path):
    text = Path(js_path).read_text(encoding="utf-8")
    m = re.search(r"const KNOWN_SESSION_EVENT_TYPES = new Set\((.*?)\)", text, re.S)
    if not m:
        raise SystemExit("package-source: KNOWN_SESSION_EVENT_TYPES Set not found in %s" % js_path)
    names = re.findall(r'"([^"]+)"', m.group(1))
    return sorted(set(names))


def main_package_source(argv):
    js_path = None
    artifact = None
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == "--package-source":
            js_path = argv[i + 1]; i += 2
        elif a == "--write-artifact":
            artifact = argv[i + 1]; i += 2
        else:
            i += 1
    if not js_path:
        raise SystemExit("package-source mode requires --package-source <dsh-session lib/index.js>")
    names = extract_package_known_types(js_path)
    body = "\n".join(names)
    header = (
        "# DSH KNOWN_SESSION_EVENT_TYPES — installed package snapshot (%s)\n"
        "# Source: %s (compiled Set literal)\n"
        "# Companion to known-event-types.txt (pinned source checkout 47f9438).\n"
        "# Count: %d\n" % (datetime.now().isoformat(timespec="seconds"), js_path, len(names))
    )
    text = header + "\n" + body + "\n"
    if artifact:
        Path(artifact).write_text(text, encoding="utf-8")
        print("package-source: wrote %d types to %s" % (len(names), artifact))
        return 0
    # verify: compare against the sibling rc6 artifact if present
    rc6 = Path(__file__).resolve().parent / "known-event-types-rc6.txt"
    if not rc6.exists():
        print("package-source: no rc6 artifact to verify against; use --write-artifact first")
        return 1
    existing = [l for l in rc6.read_text(encoding="utf-8").splitlines() if l and not l.startswith("#")]
    if sorted(existing) == names:
        print("OK: package-source == rc6 artifact, %d types" % len(names))
        return 0
    print("DRIFT: package-source %d types vs artifact %d types" % (len(names), len(existing)))
    return 1


def _dispatch() -> int:
    if "--package-source" in sys.argv:
        return main_package_source(sys.argv)
    return main()

if __name__ == "__main__":
    sys.exit(_dispatch())
