package gobridge

import (
	"fmt"
	"strings"
	"testing"
)

// applyClaudeSourceInlineFixture：与 applyClaudeSourceFixture 同流程，但数据来自
// 内联 JSONL（复现真实 transcript 行序列用）。
func applyClaudeSourceInlineFixture(t *testing.T, name string, data string) *ProjectionKernel {
	t.Helper()
	correlation := claudeSourceCorrelation{
		SegmentStableKey: "fixture-segment", SegmentGeneration: "fixture-generation",
	}
	state := ClaudeSourceState{
		SchemaVersion: ClaudeSourceStateSchemaVersion, SourceGeneration: "fixture-source-generation",
		CursorVector: []ClaudeSourceCursor{{
			SegmentStableKey: correlation.SegmentStableKey, SegmentGeneration: correlation.SegmentGeneration,
			MembershipDigest: "fixture-membership",
		}},
		GraphNodes: map[string][]ClaudeGraphOccurrence{}, LogicalRecords: map[string]ClaudeLogicalRecord{},
	}
	kernel := NewProjectionKernel(NewProjectionReducer(), nil)
	if err := kernel.InstallClaudeSourceState("claude", name, state); err != nil {
		t.Fatal(err)
	}
	scan, err := scanCompleteClaudeRelayEntriesFromReader(
		strings.NewReader(data), 0, &claudeRelayScanState{},
	)
	if err != nil || scan.Poison != nil {
		t.Fatalf("scan %s: poison=%+v err=%v", name, scan.Poison, err)
	}
	currentTurnID := ""
	for _, record := range scan.Records {
		if !record.Admitted {
			// 生产：ignored_source_only（仍推进 cursor）
			if err := kernel.AcknowledgeClaudeSourceRange("claude", name,
				correlation.SegmentStableKey, correlation.SegmentGeneration, record.ByteEnd); err != nil {
				t.Fatalf("ack %s: %v", name, err)
			}
			continue
		}
		if isClaudeEchoOnlyUserRow(record.Entry) {
			// 生产：acknowledge cursor + legacy（无事件）——同步推进 kernel ledger
			if err := kernel.AcknowledgeClaudeSourceRange("claude", name,
				correlation.SegmentStableKey, correlation.SegmentGeneration, record.ByteEnd); err != nil {
				t.Fatalf("ack %s: %v", name, err)
			}
			continue
		}
		current, ok := kernel.ClaudeSourceStateSnapshot("claude", name)
		if !ok {
			t.Fatal("source state disappeared")
		}
		batch, err := buildClaudeSourceRecordBatch(current, record, "claude", name, "epoch", correlation, currentTurnID)
		if err != nil {
			t.Fatalf("map %s (currentTurnID=%q): %v", name, currentTurnID, err)
		}
		result, err := kernel.ApplyClaudeSourceRecordBatch(batch)
		if err != nil {
			t.Fatalf("apply %s: %v", name, err)
		}
		t.Logf("row uuid=%s type=%s turn=%s status=%s events=%d",
			record.Entry.UUID, record.Entry.Type, batch.Record.GraphResolvedTurn, result.Status, len(batch.Events))
		// 模拟 applyClaudeLiveSourceRecord 的循环同步（handlers_relay.go）
		if resolved := batch.Record.GraphResolvedTurn; resolved != "" {
			currentTurnID = resolved
		}
	}
	return kernel
}

// 复现 owner 真机 2026-09-04 23:17（会话 f4c4439b）症状：
// 发问题 A→回复 A；/model haiku 切换；发问题 B→回复 B。
// 现象：问题 B 气泡消失、回复 B 接在回复 A 后。
// 行序列取自真实 transcript（uuid 截短、正文保留关键词、附件行省略）。
func TestClaudeSourceMapperReproducesOwnerModelSwitchTurnLoss(t *testing.T) {
	data := strings.Join([]string{
		`{"type":"user","uuid":"611e188f-a","parentUuid":"d1fde86d-a","message":{"role":"user","content":"讲个太阳系笑话200字左右"}}`,
		`{"type":"assistant","uuid":"475a4cbe-a","parentUuid":"611e188f-a","message":{"role":"assistant","content":[{"type":"text","text":"（附件占位）"}]}}`,
		`{"type":"assistant","uuid":"36a121b9-a","parentUuid":"475a4cbe-a","message":{"role":"assistant","content":[{"type":"text","text":"来一个：太阳系开 Party，地球喝多了。"}]}}`,
		`{"type":"user","uuid":"1492713e-a","parentUuid":"f34d3253-a","isMeta":true,"message":{"role":"user","content":[{"type":"text","text":"<local-command-caveat>Caveat: The messages below were generated by the user while in local commands. DO NOT respond.</local-command-caveat>"}]}}`,
		`{"type":"user","uuid":"79d65838-a","parentUuid":"1492713e-a","message":{"role":"user","content":[{"type":"text","text":"<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args>haiku</command-args>"}]}}`,
		`{"type":"user","uuid":"1d7e15c4-a","parentUuid":"79d65838-a","message":{"role":"user","content":[{"type":"text","text":"<local-command-stdout>Set model to haiku (glm-4.7)</local-command-stdout>"}]}}`,
		`{"type":"user","uuid":"5128197f-a","parentUuid":"1d7e15c4-a","message":{"role":"user","content":"讲个鬼故事200字左右"}}`,
		`{"type":"attachment","uuid":"b9428b68-a","parentUuid":"5128197f-a"}`,
		`{"type":"attachment","uuid":"500d8688-a","parentUuid":"b9428b68-a"}`,
		`{"type":"assistant","uuid":"325f7094-a","parentUuid":"500d8688-a","message":{"role":"assistant","content":[{"type":"thinking","thinking":"构思"}]}}`,
		`{"type":"assistant","uuid":"4a7644ab-a","parentUuid":"325f7094-a","message":{"role":"assistant","content":[{"type":"text","text":"来一个：深夜加班，电梯门开了。"}]}}`,
	}, "\n") + "\n" // 末行换行：真实文件每行以 \n 终结，缺失会被 scanner 当未终结尾巴扣住

	kernel := applyClaudeSourceInlineFixture(t, "owner-model-switch-turn-loss.jsonl", data)
	projection, ok := kernel.reducer.Snapshot("claude", "owner-model-switch-turn-loss.jsonl")
	if !ok {
		t.Fatal("no projection")
	}

	var report strings.Builder
	for i, turn := range projection.Turns {
		user, assistant := "", ""
		if turn.User != nil {
			for _, p := range turn.User.Parts {
				user += p.Text
			}
		}
		if turn.Assistant != nil {
			for _, p := range turn.Assistant.Parts {
				assistant += p.Text
			}
		}
		report.WriteString(fmt.Sprintf("turn[%d] id=%s user=%q assistant=%q\n", i, turn.TurnID, user, assistant))
	}
	t.Logf("turns=%d\n%s", len(projection.Turns), report.String())

	// owner 预期：问题 B 与回复 B 同回合；B 的用户气泡存在；回复 B 不落入 A 回合。
	var turnA, turnB *TurnProjection
	for i := range projection.Turns {
		if strings.Contains(projection.Turns[i].TurnID, "611e188f") {
			turnA = &projection.Turns[i]
		}
		if strings.Contains(projection.Turns[i].TurnID, "5128197f") {
			turnB = &projection.Turns[i]
		}
	}
	if turnB == nil {
		t.Fatalf("问题 B 未建立回合（复现 owner 症状）。投影：\n%s", report.String())
	}
	if turnB.User == nil || !strings.Contains(partTexts(turnB.User), "鬼故事") {
		t.Fatalf("问题 B 的用户气泡缺失: %+v", turnB.User)
	}
	if turnB.Assistant == nil || !strings.Contains(partTexts(turnB.Assistant), "深夜加班") {
		t.Fatalf("回复 B 不在 B 回合")
	}
	if turnA != nil && turnA.Assistant != nil && strings.Contains(partTexts(turnA.Assistant), "深夜加班") {
		t.Fatalf("回复 B 泄漏进 A 回合")
	}
	if turnA != nil && strings.Contains(partTexts(turnA.Assistant), "<") {
		t.Fatalf("A 回合泄漏 XML 原文")
	}
}

func preview24(s string) string {
	if len(s) > 24 {
		return s[:24] + "…"
	}
	return s
}

func partTexts(m *MessageProjection) string {
	if m == nil {
		return ""
	}
	var sb strings.Builder
	for _, p := range m.Parts {
		sb.WriteString(p.Text)
	}
	return sb.String()
}
